### ISSUE TITLE
can I use UCF-101 dataset?

### ISSUE THREAD

**Issue by meettyj** [wadhwasahil/Video-Classification-2-Stream-CNN#15]
hey, thanks for reading. I am wondering why you choose CVV. UCF-101 is more popular. isn't it?

**Comment by wadhwasahil** [comment]
Hey, thanks for your interest. The paper we followed used CVV for benchmarking. Maybe you can try the model for UCF-101 as well if it fits well.

**Comment by meettyj** [comment]
Thanks. I will try it.

**Comment by 87nohigher** [comment]
What is the accuracy training from scratch with UCF101 @meettyj @wadhwasahil 
Thanls
