### ISSUE TITLE
error running temporal_vid2img.py

### ISSUE THREAD

**Issue by kkhuang1990** [wadhwasahil/Video-Classification-2-Stream-CNN#5]
a float is required
ns2cQOb072Q
Fw-itI3s3mg:2852-5
a float is required
Fw-itI3s3mg
-HKADwHaN2U:2853-5
a float is required
-HKADwHaN2U
AV0rno5rBCI:2854-5
a float is required
AV0rno5rBCI
8qzJ046WHrg:2855-5
a float is required
8qzJ046WHrg
Ge4H3Jd5KOI:2856-5
a float is required
Ge4H3Jd5KOI
F5TK6aLvqpE:2857-5
a float is required
F5TK6aLvqpE
Jj-Bip23Ly4:2858-5
a float is required
Jj-Bip23Ly4
LP9kzo8Erz4:2859-5
a float is required
LP9kzo8Erz4
sbcqojEqwHs:2860-5
a float is required

I think this error comes from running: 
  File "/home/mil/huang/Anomaly_Detection_Python/Video-Classification-2-Stream-CNN-master/temporal/optical_flow_prep.py", line 75, in writeOpticalFlow
    frame2 = cv2.resize(frame2, (w,h))
do I have to convert w, h from int to float ???

**Comment by wadhwasahil** [comment]
@kkhuang1990 yes, you need to do that
