### ISSUE TITLE
creation of train and test pickle files.

### ISSUE THREAD

**Issue by kvignesh1420** [wadhwasahil/Video-Classification-2-Stream-CNN#7]
In which part of the code did you create the train and test pickle files. ??

**Comment by wadhwasahil** [comment]
Please see the util folder.

**Comment by kvignesh1420** [comment]
train_data.pickle was directly used in remove_negative_instances.py.    did you create that pickle and upload it ??

**Comment by stillbreeze** [comment]
The file `utility_scripts/dataset_format_change.py`  contained the creation method for `train_data.pickle` and `test_data.pickle` which we later changed to `merged_data.pickle`. You can dump those two files individually too.

**Comment by wadhwasahil** [comment]
@kvignesh1420 If your issue resolved now?

**Comment by kvignesh1420** [comment]
yes, I understood the concept. You created the train_data and test_data.pickle files and merged them even though the individual creation is not explicitly shown. Am i right ?

**Comment by wadhwasahil** [comment]
yes. Closing for   now :)
