### ISSUE TITLE
ValueError running spatial_stream_cnn.py

### ISSUE THREAD

**Issue by yclai1114** [wadhwasahil/Video-Classification-2-Stream-CNN#9]
Using Theano backend.
Making model...
Compiling model...
Loading train dictionary...
Loading test dictionary...
Training model...
spatial_stream_cnn.py:23: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (X_train!=None and Y_train!=None):
(0,) <--------print(X_sample.shape)
Traceback (most recent call last):
  File "spatial_stream_cnn.py", line 168, in <module>
    train(model, nb_epoch, spatial_train_data, spatial_test_data, chunk_size, nb_classes, img_rows, img_cols, batch_size)
  File "spatial_stream_cnn.py", line 67, in train
    datagen.fit(X_sample)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 578, in fit
    'Got array with shape: ' + str(x.shape))
ValueError: Input to `.fit()` should have rank 4. Got array with shape: (0,)

**Comment by wadhwasahil** [comment]
#4 The dimension of the input should be of the format [batch_size, X, Y, no_of_channels] i.e of dimension 4.

**Comment by yclai1114** [comment]
Can I alter the number of keys in temporal data pickle file?

________________________________

**Comment by wadhwasahil** [comment]
you can but still you have to load the pickle into the memory and then increase/decrease the no of keys.

**Comment by yclai1114** [comment]
How I should reduce it? Because I want to try your training but I used one day for only running one epoch.
Thanks very much


On 1 Mar 2017, at 1:08 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


you can but still you have to load the pickle into the memory and then increase/decrease the no of keys.

**Comment by yclai1114** [comment]
How would this training result output?



On 1 Mar 2017, at first 1:08 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


you can but still you have to load the pickle into the memory and then increase/decrease the no of keys.

**Comment by wadhwasahil** [comment]
You can remove according to your choice.

- Load the pickle in the memory. Let's say it has 1K keys.
- Remove 500 keys using python. To do this, iterate through the dictionary and pick only 500 keys and create another pickle from this.

or maybe try this?
http://stackoverflow.com/questions/17521379/python-remove-entry-from-pickle-saved-data

**Comment by yclai1114** [comment]
Is the main.py file being removed? I couldn't find it. If yes, Can you send me the main.py file?


Sent from my iPhone

On 1 Mar 2017, at 5:26 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


You can remove according to your choice.

  *   Load the pickle in the memory. Let's say it has 1K keys.
  *   Remove 500 keys using python. To do this, iterate through the dictionary and pick only 500 keys and create another pickle from this.

or maybe try this?
http://stackoverflow.com/questions/17521379/python-remove-entry-from-pickle-saved-data

**Comment by wadhwasahil** [comment]
what's main.py, what does it do?

**Comment by yclai1114** [comment]
I saw an issue about main.py file which I guess is for testing dataset after done training?

Sent from my iPhone

On 1 Mar 2017, at 5:45 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


what's main.py, what does it do?

**Comment by wadhwasahil** [comment]
Can you please refer the issue here?

**Comment by yclai1114** [comment]
Sorry I couldn't send link here. I just make a screenshot of it.
[image1.PNG]

On 1 Mar 2017, at 5:49 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please refer the issue here?

**Comment by wadhwasahil** [comment]
The link is broken :cry:

**Comment by yclai1114** [comment]
Can u send me the main.py file for testing after training done?



On 1 Mar 2017, at 8:19 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


The link is broken 😢

**Comment by yclai1114** [comment]
https://github.com/wadhwasahil/Video-Classification-2-Stream-CNN/issues/2

error in main.py · Issue #2 · wadhwasahil/Video-Classification-2-Stream-CNN · GitHub<https://github.com/wadhwasahil/Video-Classification-2-Stream-CNN/issues/2>
github.com
Video-Classification-2-Stream-CNN - Video Classification using 2 stream CNN





Here is the link a person asked about main.py file.

________________________________

**Comment by wadhwasahil** [comment]
I think she is talking about this file
`spatial_stream_cnn.py`. This is  the main file for training the spatial CNN.

**Comment by yclai1114** [comment]
I see. Does your code here provide code for testing after both spatial and temporal training?

On 2 Mar 2017, at 1:27 AM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


I think she is talking about this file
spatial_stream_cnn.py. This is the main file for training the spatial CNN.

**Comment by wadhwasahil** [comment]
No. But you can write it yourself, it'll be very easy.
Thanks.

**Comment by yclai1114** [comment]
Ok. Thank you

Sent from my iPhone

On 2 Mar 2017, at 2:43 PM, Sahil Wadhwa <notifications@github.com<mailto:notifications@github.com>> wrote:


No. But you can write it yourself, it'll be very easy.
Thanks.
